// Shared Socket.IO event-name constants. Mirrored verbatim in backend/events.js
// (no bundler here, so the two copies must be kept in sync by hand).
const EVENTS = {
  // client -> server
  ROOM_CREATE: 'room:create',
  ROOM_JOIN: 'room:join',
  GAME_START: 'game:start',
  ANSWER_SUBMIT: 'answer:submit',
  STEAL_CHOOSE: 'steal:choose',
  FREEZE_CHOOSE: 'freeze:choose',
  GAME_PLAY_AGAIN: 'game:play_again',
  BOT_ADD: 'bot:add',
  BOT_REMOVE: 'bot:remove',
  QUESTIONS_GENERATE: 'questions:generate',
  QUESTION_ADD: 'question:add',
  QUESTION_REMOVE: 'question:remove',
  LIFELINE_USE: 'lifeline:use',
  ROOM_LEAVE: 'room:leave',
  TEAM_SET: 'team:set',
  CITY_INPUT: 'city:input',
  CITY_ANSWER: 'city:answer',
  CITY_ZAP: 'city:zap',
  MAZE_INPUT: 'maze:input',
  MAZE_ANSWER: 'maze:answer',
  MAZE_FLASH: 'maze:flash',
  REACTION_SEND: 'reaction:send',
  FAN_SET: 'fan:set',

  // server -> client
  ROOM_JOINED: 'room:joined',
  ROOM_ERROR: 'room:error',
  PLAYER_LIST_UPDATE: 'player:list_update',
  QUESTION_START: 'question:start',
  ANSWER_ACK: 'answer:ack',
  QUESTION_REVEAL: 'question:reveal',
  STEAL_PROMPT: 'steal:prompt',
  STEAL_WAITING: 'steal:waiting',
  STEAL_RESULT: 'steal:result',
  FREEZE_PROMPT: 'freeze:prompt',
  FREEZE_WAITING: 'freeze:waiting',
  FREEZE_RESULT: 'freeze:result',
  GAME_FINAL: 'game:final',
  GAME_RESET_TO_LOBBY: 'game:reset_to_lobby',
  QUESTIONS_GENERATING: 'questions:generating',
  QUESTION_POOL_UPDATE: 'question:pool_update',
  GAME_STARTING: 'game:starting',
  LIFELINE_RESULT: 'lifeline:result',
  ANSWER_PROGRESS: 'answer:progress',
  STAGE_TRANSITION: 'stage:transition',
  TEAM_UPDATE: 'team:update',
  CITY_START: 'city:start',
  CITY_STATE: 'city:state',
  CITY_QUIZ: 'city:quiz',
  CITY_RESULT: 'city:result',
  CITY_FX: 'city:fx',
  CITY_FEED: 'city:feed',
  MAZE_START: 'maze:start',
  MAZE_STATE: 'maze:state',
  MAZE_QUIZ: 'maze:quiz',
  MAZE_RESULT: 'maze:result',
  MAZE_FX: 'maze:fx',
  MAZE_FEED: 'maze:feed',
  REACTION_SHOW: 'reaction:show',
  FANS_UPDATE: 'fans:update',
  BOT_SAY: 'bot:say',
};
